version: '3'
services:
  db:
    image: kartoza/postgis:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle_path:/bundle
    ports:
      - 3000:3000
    environment:
      BUNDLE_PATH: /bundle/vendor
      DATABASE_PASSWORD: password
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
volumes:
  bundle_path:
