default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV['DATABASE_URL'] %>

development: &development
  <<: *default

test:
  <<: *development
  database: entregis_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "").gsub(/postgres/, 'postgis') %>
